name: Devop-Projet2
on:
    pull_request:
        branches:
            - main
permissions:
    contents: write
jobs:
    check_code:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
                 with:
                    node-version: 19.0.1
            - run: npm ci
            - run: npm test 
            - run: npm run build